# ---------------------------------------------  启动端口 ------------------------------------------------------- #
server:
  port: 8080

# ---------------------------------------------  数据库配置(使用mysql：8.0) -----------------------------------#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  web:
    resources:
      static-locations: classpath:/templates,classpath:/templates/student,classpath:/templates/teacher,classpath:/static/images,classpath:/static
  file:
    save-path: D:/edu/upload
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB